env:
  global:
    -secure: "0e/Wo8w4jz5VGjGePnF0Vf4tdgQTBc1YmIJFOrn6O0gFYBurqVbgKcJ752rZVRZinHXs7D29B3LU2nJMk4GT1d/UtBmRZLpLm62zFR2pbU/2TFpmySKOBKS2vpFt7AlnEpbxhdCaB9AWTRTccXsqCxMVAb70eOuQAQz+W2hsWOlpi14B2YfKBcXSOO3yd/InVuBwd50np98Bbuh5kmLurKk8g6wjioT4IX6esyj/nJUNU8BvG5e9kG5ZLJ2ok3MN75Io4fTQlGgR6SfQjnSVluiAXi/n8+KsZHEMDyRyq+G6W97M/QwZMRcU4nbN3Ms3Of64mhFBZzJ0wwN9v789Ma8b0dYdUq8K0cuI6j4K7jG/ibK9moDDVOJ9RHrCDBjBdyCUuuF0ZVqTMbINtCvhP1JTVQsS1Ud+6DKRpm4OB2fnYb8SO/P/zJGam15hdHTZ/DLvgKVy3AcYpXpjDRj65AiXcwIjvixGS6NKgWWqtpeR87JS+8Hr0cga3G/K/SuMyIgKZC51NdwoTN7wmyGV60GLaII/wXJz+db6WZDfrc0Ca3jo+67ZgUELbzcMSVkIUKZgRNBpZh7tWwPW0iOwK5xgK32XA6wJfF2mXd5k/mQfNT8oVNYeleoOnxD/6X6KBRvkfT31mJW3RH7xU4sHGBVHERy9X+5gnCSZ8+ZklNw="
    -secure: "g12KSdR44qrrNQ3wW+GI9wfZrJedgpQKl41yAiksRKkc1wPbAgrqAP4CjiUecYxx/HLrQQW/PGsCD+0dJ2lV+dbdzVuVCQc4lhxN0yjuHca7OctSMpWy0i9vbNFi4rVxvHvwwhjd4ZR8xzwZ5dtuGoRMvPUK+ry4MJ41rJM9VOHdY1JSBltdnK5vNy/apz1NNeTmlOlOZwz1TOQVEW7xXd/pau3Iy2wxOt1dwoi1uroeOdBchFvB5MAczVQcyOqQ6Gilw+WEFv1FT+02d/7Pt3lN++FfK6ccm8SOGWhoYaI7K4lir5uEarhoPL+pOm36uIg+PRLhW8Q6KJHC7feO1mgJA5B752EyozSZmblUtsiC37wf+fWamaTfVli8FMHgg3VBOe3zcsgiBfV0ocZwqYlkNFJKcF7inXjX1i8OhhlWtCTn3JZ5DXueYETOl8dPGSBb6VTZkN6LqBmHucBDJCY+O4P3/KSoNDQcz3GpRcDvFi3pN+2PYzu9B6DmK7nqo9zbQRh5Dip1uPUHpg0yNB8SutywflQGjXt9Tt+guh07yb0sZD/EN00ZrCS30mBKFrK9jD4h9PMxc4Ja5C3Czw1xXRqoaagTkNqz1VKjdUo5byOrtap3za/u8sNkbCTFdslsyta17vmNOKF8S7ozB1+5/E12e0jKtMkkOGxc34c="

matrix:
  include:
    language: scala
    scala: 2.12.5
    before_script:
      - cd Cores/ExtremumScalaCore
    script:
      - sbt assembly
    after_success:
      - mvn clean deploy --settings settings.xml