env:
  global:
    -secure: "dViZ4YMWIt8ZojPla9WnoWJiLN6rZ3JYGxinCOrFKCrhUYjd05YDxuo8MJUeewOuyFppfwHHIDwGhDSMD88rITFEFt3JutT/QkAenux3emwzH95NMKWGljO0sEm/AEi/pPFoYKqefBZGyKX4jb/D3x3usx/9JrDENepBbs4Nz7naiCApvI3pdBfDJ65lXqBdPcqj6fSutmbfLVj8xbRKF7tYRbkUTTUrgI6WzFNBvYu8dWU5gHCENuSeOr8wAtJkbU+t6b6uA9pzSnXiPVBNyxQDQ+debnz2r0q9Dm527inaMpf4IL34rI6Is/qraE0toafnJp5S2lAFBOCTt90ul2Atr2SXLtpXLu/oGxPN4qJN3AOT/qP19/bsTKrK4l4xGIP0uASPwqudpPo7Kn7TXJCgPEtf+H9v2bLE9jtiPD9AuRIjU7SDFjea4EGpbFrqTTcLnMwQaAmpx30UW9kwuxQOcoUj44oB23nuPDWVojNrt/onqpEBI9dwtMtag2IIycgT+G12NTpAhvhtYATsus0qY+/PPTsySTVS7Ip1tm8cajt3gUcpBhw3wgsDxPCtwvIhQRCcwIrkvPobSmF/7JCAHNIul77QshtuE8+1vYEoq0jyFNeypa+CygIh5fvsQtZL/ORbh6nBwXMZQLW3+3kkqzvAp6LCN958XDcJ1ZM="
    -secure: "JOgFsf3X6R56xX5rO2n571AJKYe9taRMmequBqbFv/KUfHrrJmNsU7/hmifqIDQ9R9AFX8TrtzWWWog2l5q42m7COl4h/WdzGFkDuwTJd1L1vKpp1miiE8PEmyIDQNjJSEXSLncoY3vbmwNk6zveO/ALkDxSdiM+fyw57IHPcSfvAdAqd2vO8BMUrslvFzr6eY+kIIeF9JXffV+HvXCzBTTdymLadhy9B1DyeDUN7s9vhT/Fot0HKV5i3gSB6XcwD36yXk0FB27a26WEdEb1mvEnwsKjkAqiQabsJUDlO387MBllkCbwQsvSeZzOjSc5EeGEMCjBjBVdZeRQFdqsghh6SK3B1rpnFxIBUzPh+ht9/fHEFeWHTlPc94SCbA2qWJygJ2OeCEns5drRCVO7raSX59Cqj9SKH+a8+sNKxQypgHmU8zdBEWOdk3ET88gB8GYLlq16rPMeUqj9xCuEsvBxsAjtAm/Yxp22tWfcqSTet1cY4+JdIb4I5WFfVYbuXftSgoDVYR4FrUTg3dS5TZZHtA8uONwEAuLP7orryDKl0qSNEKuleYPmeEvAdHr5GDNtmoHaDq8Kfvqb9Fsk9qZtlfXEWkPfniQUnvDdwJdMUR0FOVhgORKR/9WdacvEcpBrYDhZUcPnFvR1O+gjk4ZwzXz8RDjEjS8Dous7sQU="

matrix:
  include:
    language: scala
    scala: 2.12.5
    before_script:
      - cd Cores/ExtremumScalaCore
    script:
      - sbt assembly
    after_success:
      - mvn clean deploy --settings settings.xml