language: scala

scala:
  - 2.11.2

env:
  global:
  - secure: "YId+7lQVZWupiCawZLm8YzDMQKpcUrYuOTZTM8OOPGOqwuBLkg9ShCNuqdACzDFZbkkNKVYMPO1Rb7jGJr1yFMnQhkhp8fSZa0qrLkw//WpM70k5gJsPATi9qikL+tyareLysLdYxkoaQid+HkeUzMUCxX46kqDxmIduJeOQBl6IKaKwfeBB7kk49uk18UuhgLCQAcdhaLqO4Ql4dQyjcCFaxbcBsw36I7i5HeX60bT72lmHebwIJ/83eORG1ejqKSsImgOjlT89EheQlMiGnfZLJlej9AddOMwo5VRdijNm7t3zWP1e0QnX9g6BYxH4zXXrZDNChnBARoYPk7cRa4iXwv601FW8CHMccA7jBM/j2JldJ3CbEp1C5x0uBjS1OxwIVFOOWaagnPweOTyZMKSe3fTvIOhDU1/S7jSOBoY8TeTPuqma15wiEsqaEAwcJnu2yYQFSX8PZ+rHthsGyBwftKZOu0N/mxZuac8AhxTdigs/K/4rk7UbhxXrUQ7wztIHC7BJNSFMOIMQKdtT4PrLKdcnPnJiceUKMHp0O/573jE+Br7Yv7w9sY+c8FEdstVuMVgfU4TIuZRaV2fYtn9plWmK66Ye/JoXlbAQmu104Y6l/4f05Ww9o5awFyy1vQnVxR8SWPSQgv23kZUEsYt1fZss+o1FZZAicDR2J40="
  - secure: "w5o8sauIz/WQms+IwzHzWf6xiq7Dg2oVWq2Q41KpNkhyNUynLkeYukrtXktcKjlbrLyKFXgdhYs/9qou7C510vHsh8FgokD9AGALDNoP7Pg5R/KRNLEk1hIlFGKWftxlQabg2aO435BJcN7czcL7lOFYCFNeoHebkSMEU7SCX4cetUaaiXluk8Yc08hmK7oP9P7mpdCr86t3Mp4NK0/8k/qXhRnHwUKHqrbMjxafvx/g8+uT2K1QJ2gZYo79IUz4LcQJrrm+bnkZL7uq/8gh3eXkvHtn3ZUbdF7fV88932HXlgJOx2Ue2qypubdsWsoX//AvCys+a9ehcfuuOmwICuphPbG7IBpfCgQ9hNbxQS8C1uw9qOgaQhPmhDxTx2jCwpJ0rMNPYvLXGd10NVdOCI+k9r1zTwmeKcgQAIrZ0vkNUGXfWSxnMH0Ax0iMX69BhefwoYQ5CwMD4LQLeRdGkaG8QJRwFCbVhCLKNT/7SsGfT/+VNaZHM2o7OylGydf942IyTeXetKrzLOdGlRXKnwe3PgigNjMcbWwE/wdvWt79fuIujEMV7EaMGN+H4eANPeEmNcjMvwHhLWvnW1GaycM+o+LZC7ycHyw1v+xAeaaS03rNK0Rs3IUSUTa1nQwtNFeBQw4PU5lVAkiFbcvZKXpLsNTEcymo4cCrpAf5B/Y="

script:
  - sbt clean coverage "testOnly * -- -l kaimere.exclude_tags.PythonTest -l kaimere.exclude_tags.MatlabTest" coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml
