language: scala
scala:
  - 2.11.2

env:
  global:
  - SONATYPE_USERNAME="wol4aravio"
  - secure: "otuvglURALN45aHEX/CNGUGb5/m0LhaAn9RXFw/rBhAMXjHDFLaZuNVkd8TrBHuQE11HPPHC054Ae8eiy8aEZ0gHJeiNrPBJ9XuJTFt1GOSuBs8BZIjRalHkFvwJDynThf+TDWt/R5rge7w06IV1JKFskVTscxiPZ2FCobrj7xRNI/LfMqoeKGy3qTEWrb7fVCYeA+FNJEtIKPMkmcwaKNSQS7uuXKdz1A/B9YSoyKuoNJ7w5t3KpjBw+oCLJagA1r7DePIJtrLUSInDoLea1GhJvPq3AAVCuSC+fFj1ld3SfLXKzTH6Kva9PTSVOm5gaqDBA6Uu2393F30m+fSC8YYq6qf+DHY86YJiG3brw5Q50Ht37YOJAa3+P9PEQ8YDvnnxmCxAQ4qPoj8fYjpv7MC4S0TmQaL4wsf9dgwCTtI+k2/bzhSVG40bBlXPlaGd2G7UmGGXaT2brRHLLR0/6hQOuYieUvROnd1YCCOQTFERsXeD1wvjgQjPYsQGALi374NPj/RoGZsaSLehiDjernVAbu8rCoZNBg/ihmiH+Z/RqTniQEv7L0881DVZfZUWCkCLWEDxMe2yO0L8v/nQdUw083YQOteiGnNWgcOjUn9CzKJuFD9FN3Xeu5fgpDg5+5Jz2CSYtFN/PYz8CDr4nltCBK5ekC8fGiIUzkAOiuM="

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml