language: scala
scala:
  - 2.11.2

env:
  global:
  - SONATYPE_USERNAME=wol4aravio
  - secure: "AH9xb7NRLFDN7XLgBGBsEuFn6XmSdsTGXlb4qPMKNsTsfpmqGzXF2t+mxIfwGedGHI2wqiqLDj2xOomWmeYJuhKApv/E8b09S0WIyogKu7YRqmInxsVB8ELeaPkf0wp0yWmJEIJL4dU5Vu61zBTG8FUs5kyjK8JEFFZ5gLnndoA8BcmKCBDTz6h7hyvTElO6cICNXC6Hzb6YbzJ17Axg6Ur/U1ld3wmb3TQkHu4yl2Qll39P6pDl+5Jwn4ALlCwbjuRbhOxwUbdrDg8Po+p60CTBCWXir3OYSITzLHn9lyVfv0wPcC93dyD6/D41ENwP/VvSkR662c1z2tuyHf1LgYojKZ0AtVya0fQnGir4XtpdqQUwqm4q7RNOvEVRvbPzbC3XpG95LqCD8HPJNsnadm4tuhAwo8lYmoQOY2s8dFuGcc1KaJp7MF+xobih4zudm3zEc9FpJo881QP7IQoZWKYRPCN/42J9jyFGkVPEGshufvNsUnQZmgYX1NLriu3lJkDxs0qZVY9SxuzKre4CY0w+nW95wS8G8o1K+hnSCMo+DRW8jM0Jb85drP1PjbQMCMqd6Nkj0kGNILvHqaPKK+U4Cg40HPlyL+LrGJH2Ka6XyBU4jkK/0yXjT+wSUc616H8DvRpBrTUxY4AD9eAah+tat6TDNlVClbXmVRnZp1w="

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml