language: scala
scala:
  - 2.11.2

env:
  global:
  - secure: "ATv2oESzIUXT+/FO15U0fK+9I22u7S1ntyqhS4Jq2YR8BA61C8FgMWRnCsn/Rmrqz22jNWRvDuUVk+L8xb6KEXPdA0gxnj7ZHEb9LV8Z5zLPdqx7znQLyQtPDnTP5xFQPdIUmn46Q8HX4t84uNFk19bugy5Z6SwsLs78z5V/7TjvA7W2NMvo/3fF3hP5Gv3aO1S92jp/cXR/L5uojv7hjTwAtabpUUXwYApkbws/MK4t8aIz52Nvh6qB9Dm16ZXGw6/AuRGXF6Te4389mBhfr+S0qJoKd1MVpiA1mDbqPRkVLUNOq8UccVGrHtFu6xHNv4VfmXN6lNmkMVDPt15CiWioyl1CnEVKqFyek96yyhw0UyTEDug+R+SF79bB6Pco26yxpvtZVvAYQgpiWleomw5BvplSOucyLrMddbA4DXTHsIYDZRccu7S2LlLmeRFvghSvnO6hMxD4MFJVCuenGOceeb9oyqVbnfPXBj5YBgHTZn56QDRD/J48w0PF+H4BVqJsSIgybtkNyeLrsYQZA6c7aF5ZZ7KrLePL3dVsF62CXuqImt3Ccd4qYARljwICRRFRIsRDjoayPvECW1evbtU63lJyiKDeT2VRb6gI36YolkqjeNZbe1iALoBKgL9IwJK6ktTHIojI5vju/9I926T0sSUs/DrMGfLmiEIUuTg="
  - secure: "ZIXZh27UCyZItHeV1W5QJWfnhLSuMUO+d+oCSA44rq0Ahbznqtf4PRCVbMJ/8qYpqlUCSU/E5SlYaAu6Kbz4YsSFsX90rAnbcd+HPOrhhi68Y/jH6y9WscfWQMa58cJGiTk8b25/wvKLE3ZuJeBHOOGP3jOnnpqwFQlOgcTNa2Tx42NbMZasOwTgE34L50mKKESmiBm5pytGVilWdhgHPxZ5BCWDODazie0yJuEMEkcMujGcAYzVnqL1t9D+LCZUAQ3WXsSXZ5WqUHITCSS3N7Ken/sLmkjb2gQiGrgQHhivG/HID1AILIYi3F5yNpfJDRS9SjouAbt3BVAlAoGZTS1uGjdgn6Dr+Jgdtuce04icFdDP+j3u/7Sw0k4sEoq/FCNY84UgFdhXEGmvj2tJB3DcV1zr6HEaxOMvDvyMa5nOX+NkHVb63W8E6j0u8Xr8JhfGApQZxVulzzw8856d2XuOP1dq7057m8SwySY018ElSZggvuFlhYaAJpDy/cWesMxsXHoJO1GF47uQ9UtC3mWZQ+v+EffkErc1OMROCod5BW60t3paQ1ReKu2v5Sq2mpwkSF5zXCZ9NE+PK5r8hAJpi1XZ2upKTYJ255/SV7vgbRohgbQBCTVmHWNxKxptQIMJIqXQnaRRnL3HUzYM6KfgDWcdH6QmpnyvRsees80="

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml