language: scala
scala:
  - 2.11.2

env:
  global:
  - SONATYPE_USERNAME=wol4aravio
  - secure: "AvvMF4Rv5zLdvOQ2DGd/4xuqJz6ktgm0N2VfoYgGXC0EZnwKcki5i9kiQ3azQI0Uh3DU0T+Rc6YaRZvHzA4RZswieH9+Qs5V1xeVsq524I9xATUVQIPU+VvIHoZD196M8+tx9z6nBOs2nmv8Zm7vjUNuaOYrw7EIcUJHm7mKcoqk1dyfqVn/LUNkzJsda4Wlj+gYnulKj+s7kc/foGgCSQE5qePPGH4KBGWKCnRwZG8sJJBgQLN0RONxVevTC4RptYwvbU0K1TsXjA5i9aC3vA2/YVka3kkDjScz5zrQc59fnrX7EMPTptUfX8+2IyREfyLfBiGpVIjFpW/KqP7bQN8FCCb5fjYp6tLCYBMO8FON6kjm5viv2FgSyTOdhqVJHkRSnihW4I8/uH15JrY4Oc2PuocoulMtejded1Y6ydm3PuXcQ/kKTA+oeNUiYl/zA46BIw3JWfOGpMwbNKnEB0hcqVHi+zi1qAKtcyuAQMy6AzSgipEXIlDSGpAzDV6NzlRgrhHYouXcYDwMycg7CSk0ny2WXNVGOe7Q/SafBCaphjRSO3hgZ4ScNcAroTgGYs9z2xK8VygkP6GMLR8wKTlGcSHlqZD0jgPi4C7kDEZ+gcpMU6ELews419bhvumeLmvjLWMrjv2ryyS1rxDesnMy9cOyFoCX5DICXmoXqaE="

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml