language: scala
scala:
  - 2.11.2

env:
  global:
    - secure: "z86uFRJUF8LMvPe7E07LwccHM3q4fbI6tfZWKRb0REi/8dBBg9FrpdP11ifSJ63pnOg17NBrHCyHEdx2XO9DKymBU4xl0Oq3x8MoyyCDsSq5kWV9hrEsq75MZFipXVmMGc9HFZCkhTieH9a+0u7tZ1qDAM5fDTdhcklz+J6c/cIXVt49IzjQAoIFvs+PXSf4xIx56VozqKlEiSX5ICrgFdjYqdv5VHLAbKMSS1/tpWRxwUAkFBEAfiSKTfU0ZblountPDVOI41kjWml4yUgpjvQRCZEbKSE8t7+vXhx7ycJ6c+nEdouYtKB5Q6S0gjwNUIsvJLkgQ9mbd79LlHBf7DVlHZaGGG6rFIFsQJOET+OANCjU4AXdc7pMwX1TRWpsdafPMU4bp8swnu5EstAQVQbdD83Tp2P0PkS8P+nAjICX/h4AaLuO5fMPOhrxbwnltkAdN5r4VO7E25s1SGCoF/yfV4G7aFlr/KpjribJg3Ior0YoNzW+yk1onReqU5lWz5l5mHoH7qr524vDokJHjjNubljNVRZFFp2On4gMM7PmdKnMgxF9ItyRDFcAPXEQRLG5RQOwmg36N1j+toFL4HK/Au9EEPEeB6akaAe6h/mqb9WhwZv4jWWlSOqmU183qpJpnrGtg+Sx3+W9Y97wuE1iruXETkYhWdLRm4D605o="
    - secure: "SwdsGFQcHQ9aaggya+S0yOuKkpNTsIGU+VVdFl6Kk39vtLL61JuQ7zMzvNlqLy/h55lAxQOZF7bTD5wxcybk1FCOcZdfRByKQsDnR67PnDS/T7c33E+UrqjEqG8oSuA1VuFIFxgdyYufy87ps/q1rBE1ElqI1L+8bFWYXFMZeCxvwxahD+h/XL8XWa90qBt4xjP70+2VNvprLe97YArDUiUUZPJGj7LfHWuI9itBdnjEUusnQiD19bjBOXFNt1dWCQtgexHK5qV0J1ImbFZffkxTDNMp43bMZ4OiqWVtV6zOEFfYnWxrjHwpn8dr6ZBdVTdce/kqYbzwhmW5UDAbudl5GJOrlrX/e2UiuRz3WX2ZylJJypSGj/31kIx3Zo4KQaSihY5jrE+9mfHSU1s18X59R8s6/nCAtSjtJfezv0Gr5FBxGBA5Y8JUQbuHa1EDLvAFNMsnGbw4V0dvLGmXaLDVREPA0ZNlubHiAvhu81RHSPIL0MEV/3pGTqPFyagENG3AQWrGw8CuSrrXg3vhTiA2ELPM287ea30IgWI/Z8m6xt2wZAjvqV0/3j5i5Vuqkt82iALSgbkAKfJS0Mik6Tg4JYbIu/yebR9xw/TT9DN9SqiCHPo0Gc4Q9pSm2rctJWf1mArTRlDdl06iAyPK9L06D5CTe8uZIwyOfeKW+pM="

script:
  - sbt clean coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
  - mvn clean deploy --settings settings.xml