name: CI & CD

on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  coverage:
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.8"
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip install poetry
        poetry install
        poetry run pytest --reruns 5 --cov=osol --cov-report=xml
    - name: Upload coverage to Codecov
      run: curl -s https://codecov.io/bash | bash -s -- -c -F aFlag -f coverage.xml
    - name: Publish to PyPi
      run: |
        pip install poetry
        poetry install
        poetry publish --build --username ${{ secrets.PYPIUSER }} --password ${{ secrets.PYPIPASSWORD }}
